import {i18nIns} from '@/app/i18n';

const {t} = i18nIns;

export const STATIC_COLUMNS_LEFT = [
    {
        dataIndex: 'deviceId',
        title: t('设备ID'),
        name: t('设备ID'),
        align: 'center',
        width: 100,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'deviceName',
        title: t('设备名称'),
        name: t('设备名称'),
        align: 'center',
        width: 120,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'deviceModel',
        title: t('型号'),
        name: t('型号'),
        align: 'center',
        width: 80,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'farmName',
        title: t('电场名称'),
        name: t('电场名称'),
        align: 'center',
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
];

export const STATIC_COLUMNS_RIGHT = [
    {
        dataIndex: 'deviceId',
        title: t('设备ID'),
        name: t('设备ID'),
        align: 'center',
        width: 100,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'deviceName',
        title: t('设备名称'),
        name: t('设备名称'),
        align: 'center',
        width: 120,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'deviceModel',
        title: t('型号'),
        name: t('型号'),
        align: 'center',
        width: 80,
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
    {
        dataIndex: 'farmName',
        title: t('电场名称'),
        name: t('电场名称'),
        align: 'center',
        canResize: false,
        canHide: false,
        canDrag: false,
        canDrop: false,
    },
];
